### ISSUE TITLE
Curbwheel measurement not matching Adirpro measurements

### ISSUE THREAD

**Issue by russbiggs** [sharedstreets/curb-wheel#123]
The readings from the Curbwheel seems to be skipping measurements compared to the plain Adirpro readout. Given a test along a 23m segment of sidewalk (measured with Adirpro) Curbwheel only registers 12.8m along this same path.

**Comment by russbiggs** [comment]
@emilyeros @molliemcardle

**Comment by emilyeros** [comment]
I see the same behaviour. 

For a set of 5, 10, 20, and 50 metre distances, I got:
4.3, 9.0, 15.2, 30.9
and then on a second trip:
2.9, 6.1, 11.7, 27.0

If I walk at half my striding-through-the-alley pace, it's more accurate:
4.9, 10.0, 20.0, 50.0

This comes from the debounce setting. We can desensitize this to allow for "faster" walking. In reality I was probably going faster for measurements than I would on the street, since during surveying I'm paying attention to signs and never going very far without stopping to record something. But I was still testing within what we could consider 'normal operating conditions'

I also wonder if we really need the debounce or if we could get preclude that by using a less simplified way of tracking the state changes (see [https://github.com/sharedstreets/curb-wheel/blob/digitizer-v3/parity_wiring_and_scripts/counter.py](alternate method) (and/or avoiding trying to track whether the signal is rising - just read the state of the pin. if it's false, then it's falling). I may just be biased here towards the initial python counter I wrote.

If we struggle to get a happy medium with the debounce setting, then it's worth poking around with a slightly different state tracking/counting method.

**Comment by russbiggs** [comment]
After adjusting the debounce time to 50ms, I did the 5,10,20,50 test. I made sure to keep a pace around 1m/s, a little slower than the "normal" 1.4m/s (according to a google search) but this seemed like a good pace to get long segments done more quickly. 

I got: 
4.9, 10.0, 19.9, 49.8

**Comment by russbiggs** [comment]
This seems to be an issue due to the code in R8 not being add into SC on github, so any upgrade_wheel work overwrites the value on the Curb Wheel (I believe a debounce of 1ms). Easy fix will be to get python code on the wheel merged into source control.

**Comment by emilyeros** [comment]
closed - issue addressed as part of app overhaul
