### ISSUE TITLE
request user location and bearing

### ISSUE THREAD

**Issue by morganherlocker** [sharedstreets/curb-wheel#36]
We need to request user location from the browser in a way that works reliably cross-platform. This will be used to focus the map and follow the user puck. `watchPosition` looks promising for this:

https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/watchPosition

I'm not sure if there is a spec for user heading, but we could at least infer it from positions if needed.

**Comment by kpwebb** [comment]
Looks like heading is in the API GeolocationCoordinate object:

https://developer.mozilla.org/en-US/docs/Web/API/GeolocationCoordinates

**Comment by emilyeros** [comment]
note for clarity - this includes adding the map focus and zoom behavior into the UI (not just the "plumbing" for it)

**Comment by morganherlocker** [comment]
This shipped. There may be additional work to configure network to allow the geolocation API from some browsers. The PR here also implemented a graceful fallback to zooming to the graph bounds if the browser does not support geolocation (it's bleeding edge still) or if the user declines geolocation access.

**Comment by emilyeros** [comment]
Browsers will not allow the web app to retrieve geolocation without an SSL certificate. We can self-sign a cert and it might work on iOS but it won't on Android ([related discussion](https://raspberrypi.stackexchange.com/questions/91154/raspberry-pis-local-hostname-doesnt-work-on-android-phones)).

Here are a few pathways / wild goose chases to offer, in addition to whatever you can think of, @russbiggs :

1. Use something like titanium to make it easier to turn the web app into an iOS or android native app so it can use the phone’s location services. downside: have to release versions through the app store, and that sounds cumbersome/undesirable/more brittle.
2. Put a GPS hat onto the Pi instead of relying on phone’s location services. con: one more piece of hardware, not sure about accuracy. it’s amazing how much functionality exists on the phone but can’t be accessed bc we are in a weird purgatory of network barriers. pro: may be way easier than software modifications. [Related post on a discussion forum](https://tutorials-raspberrypi.com/build-raspberry-pi-gps-location-navigation-device/).
3. Keep poking at whether we can have a Pi connection over wireless and a cell data connection. we looked into this a while ago and didn’t get a conclusive answer (there are some [older discussion forum threads](https://www.raspberrypi.org/forums/viewtopic.php?t=202271) with mixed results). in the past we’ve peered into this hole and followed some links, but didn’t get as far as trying to implement something; it didn’t look promising enough / we didn’t need it badly enough. if this were possible, we could host the web app on gh-pages and access it via cell phone data, while hosting measuring APIs and other processing on the Pi, accessed over wireless. data still gets stored on the pi, we just have a real live curbwheel.io website with an actual SSL certificate.

**Comment by emilyeros** [comment]
closed - issue addressed as part of app overhaul
