### ISSUE TITLE
orientation selection tweaks

### ISSUE THREAD

**Issue by morganherlocker** [sharedstreets/curb-wheel#47]
@peterqliu The orientation selection looks great! I find this style more efficient and intuitive than the flip button I was tinkering with.

![Screenshot from 2020-04-29 15-54-22](https://user-images.githubusercontent.com/814300/80654711-c1f04100-8a31-11ea-9422-09089dff5bc0.png)

Couple questions on the design:

- A,B work as placeholder symbols, but I think these could either be dropped or replaced with something that gives some information to the user about each direction. Maybe arrows are all you need? @emilyeros might have some ideas here, but a couple possibilities I can imagine that _might_ make sense:
  - forward / back
  - left / right
  - sharedstreets references
- red/green color symbology will be difficult to distinguish for some colorblind users, and I think red/green can sometimes have overloaded meanings we might be able to avoid (ie: on/off, enable/disable, etc.). Any ideas for a different palette?

**Comment by peterqliu** [comment]
Great points here. Open to all kinds of direction terminology, though forward/back and left/right make sense only because we have a canonical `forward` perspective from the OSM line geometry, which end users might lack context for. Same for shst refs 🤔 

Also, considering adding buttons for users to tap as I had sketched in the original wireframe, instead of direct map interaction... the map automatically pans to encompass the street when the users selects it. However, if the street is very long, then the resultant map zoom would be very low, and the two sides render almost atop each other, making it easy to select the wrong side.

![image](https://user-images.githubusercontent.com/4551508/80656677-9a4fa780-8a36-11ea-9535-37959bbb921c.png)

**Comment by emilyeros** [comment]
i think this is conveying two things: side of street, and which direction to walk. That's fine, but it might help to clarify in the label that we mean both things. ie if you add the label buttons at the bottom, then rather than "Side A" as labels, could it be something like, "Side A, walk in direction of arrow" (or a shorter description that will fit better). 

Or, during side of street selection, could we change the header bar at the top of the screen so that it says "Select a side of street. Start at the top of the street and walk in the direction of the arrow"

**Comment by emilyeros** [comment]
tracked in https://github.com/sharedstreets/curb-wheel/issues/85 and shipped
