### ISSUE TITLE
GeoJSON format exports

### ISSUE THREAD

**Issue by morganherlocker** [sharedstreets/curb-wheel#58]
Export a geojson style set of files from the graph. This needs to be exposed by the server which will then be exposed to user through the admin UI.

**Comment by emilyeros** [comment]
Below is an example of how I think this should look for the initial round. (Draft for discussion)

Rationale: the reason we're adding this into this week's app version is so that folks can see the data that they surveyed by dropping it into geojson.io or QGIS. The moment you drop a geojson into GIS, any nested properties become nearly impossible to interpret. Any long property names get truncated. So I envision this initial export button as a way to create a fairly plain/flat geojson output that is simple to open and read in GIS. The output should include geojson features for both the span geometries and the position geometries. This may not be the best structure for data going into the digitizer, but it's a way for users to take their data and exit away from the SharedStreets pathway. This wouldn't just be a need for this week; it's a long-term desired export format.

Complications: this surfaces some elements of the client-side data model that we spec'd out last week, but it also mixes in id's and other properties that we decided would be generated on the server side. It also introduces the adjusted distances, with involve centering a survey's distances on the street reference before deriving coordinates. Property names had to be truncated to 8 letters to be shapefile-compliant for those importing to ArcGIS (i didn't just go rogue on the naming conventions). If this is too much to add in, then we can walk it back for this week and generate something simpler instead.

### Example geojson output for spans:

```json
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "created": 1588833685540,
        "ref_id": "absdf123",
        "side_st": "right",
        "shst_len": 461.6,
        "srv_dist": 441.6,
        "feat_id": "xyz987",
        "label": "no parking",
        "dst_st": 220.5,
        "dst_end": 405.7,
        "img_ids": [
            "123abc", 
            "234bcd", 
            "345cde"
        ]
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -108.5013735294342,
            45.794272305650665
          ],
          [
            -108.49891662597656,
            45.79173634524376
          ]
        ]
      }
    }
  ]
}
```
Image IDs will be mashed together in one column of the output when it's read by GIS< but that's fine.

### Example geojson output for positions:

{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "feat_id": "xyz987",
        "pos_id": "012zab",
        "type": "span begin or end",
        "adj_dist": 15.1,
        "raw_dist": 5.1
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          -108.50130915641783,
          45.79430970833295
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "feat_id": "xyz987",
        "pos_id": "123abc",
        "type": "image",
        "url": "https://i.imgur.com/Fl8HQpU.jpg",
        "adj_dist": 224.8,
        "raw_dist": 214.8
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          -108.50080490112303,
          45.79385339389408
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "feat_id": "xyz987",
        "pos_id": "234bcd",
        "type": "image",
        "url": "https://i.imgur.com/dNE2Hlh.jpg",
        "adj_dist": 321.4,
        "raw_dist": 311.4
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          -108.50062251091003,
          45.793643936834954
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "feat_id": "xyz987",
        "pos_id": "345cde",
        "type": "image",
        "url": "https://i.imgur.com/Yhb2bJZ.jpg",
        "adj_dist": 415.7,
        "raw_dist": 405.7
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          -108.50032210350035,
          45.793314788437215
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "feat_id": "xyz987",
        "pos_id": "456def",
        "type": "span begin or end",
        "adj_dist": 451.6,
        "raw_dist": 441.6
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          -108.4989058971405,
          45.791796192246544
        ]
      }
    }
  ]
}

The spans and position features could be together in one GeoJSON export, but that may introduce some trouble for ArcGIS users. We may want to consider splitting into one LineString-only geojson and one Point-only geojson.

**Comment by emilyeros** [comment]
Should've mentioned earlier - I used the Span example from the data model (https://github.com/sharedstreets/curb-wheel/blob/data-model/data-model.md) as a starting point for this

**Comment by morganherlocker** [comment]
Retitling this issue to reflect that this now refers to something different (exports)

**Comment by emilyeros** [comment]
Just tested this. I mapped a 5m-long parking zone, 20m-long loading zone, and fire hydrant. I end up with linestring features with the right start and end distance, but every point in that output has the same geographic coordinates (even the from and to coordinates are the same) so all I see visually is a stack of single points on top of each other. 

<img width="1520" alt="Screen Shot 2020-05-26 at 4 54 19 PM" src="https://user-images.githubusercontent.com/9657971/82961417-30151e80-9f72-11ea-9d15-d1e88555a98b.png">

geojson output:

```json 
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -121.32284812511429,
            44.06062295925866
          ],
          [
            -121.32284812511429,
            44.06062295925866
          ]
        ]
      },
      "properties": {
        "created_at": 1590537096322,
        "cwheelid": "",
        "shst_ref_id": "1242a5ba39bc84a2dc614ce6268ad1b9",
        "ref_side": "right",
        "ref_len": 142.1026129711061,
        "srv_dist": 38.400000000000006,
        "label": "Parking",
        "dst_st": 3.200000000000003,
        "dst_end": 8.100000000000001,
        "images": "[]"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -121.32284812511429,
            44.06062295925866
          ],
          [
            -121.32284812511429,
            44.06062295925866
          ]
        ]
      },
      "properties": {
        "created_at": 1590537096322,
        "cwheelid": "",
        "shst_ref_id": "1242a5ba39bc84a2dc614ce6268ad1b9",
        "ref_side": "right",
        "ref_len": 142.1026129711061,
        "srv_dist": 38.400000000000006,
        "label": "Loading",
        "dst_st": 10,
        "dst_end": 29.900000000000006,
        "images": "[]"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -121.32284812511429,
            44.06062295925866
          ],
          [
            -121.32284812511429,
            44.06062295925866
          ]
        ]
      },
      "properties": {
        "created_at": 1590537096322,
        "cwheelid": "",
        "shst_ref_id": "1242a5ba39bc84a2dc614ce6268ad1b9",
        "ref_side": "right",
        "ref_len": 142.1026129711061,
        "srv_dist": 38.400000000000006,
        "label": "Fire hydrant",
        "dst_st": 37,
        "dst_end": 37.2,
        "images": "[]"
      }
    }
  ]
}
```

**Comment by emilyeros** [comment]
I also noticed that the `created_at` property on each feature seems like it's a timestamp from when the data was exported. can we change this so that it's a timestamp related to data creation during the survey? this could be either the time the feature was marked as complete (for spans; for positions, this is the same as the time the feature was created), or the time when the survey for that street segment was marked as complete. Whichever seems more logical to you or more elegant in the backend.

**Comment by morganherlocker** [comment]
> I also noticed that the created_at property on each feature seems like it's a timestamp from when the data was exported. 

Looking at the code, and I think the created_at property is created on the frontend when the survey is uploaded. If this issue persists, I can dig further.

**Comment by morganherlocker** [comment]
This shipped: https://github.com/sharedstreets/curb-wheel/pull/80

I have address all feedback in the PR, but please open another issue if any additional feedback needs to be addressed. :bow:
